### PR TITLE
feat: don't inject generated files into hook command

### PR DESCRIPTION
**Pull request by melloware**
this fixes 1 spot that `afterAllFilesWritten` was missed

### CODE REVIEW

**Review by Arkanii — CHANGES_REQUESTED** [review]
For me this PR is a BC, this will generate an error for each Orval user if this hook is implemented.

You need to accept both functions names, and deprecate `afterAllFilesWrite`.

`afterAllFilesWrite` needs to be removed in 7.0.0 version.



And don't forget to update documentation:

- https://github.com/anymaniax/orval/blob/master/docs/src/pages/reference/configuration/overview.md?plain=1#L63
- https://github.com/anymaniax/orval/blob/master/docs/src/pages/reference/configuration/full-example.md?plain=1#L59

**Comment by melloware** [comment]
i will revert it back to allFilesWrite then even though it is grammatically incorrect.  ITs an easier fix in the short term

**Comment by Arkanii** [comment]
Just revert the documentation in https://github.com/anymaniax/orval/pull/1181, I'll accept the PR quickly.

**Comment by melloware** [comment]
Yep PR submitted

**Pull request closed without merging**
