### PR TITLE
Add type discriminator to subtypes

### LINKED ISSUE #423: Discriminated unions with identifiers
I would like to know whether its possible to generate TypeScript union types which include identifiers to be able to easily distinguish between subtypes. For example if I have a swagger file like this:

```
components: {
  schemas: {
    Shape: {
      required: [
        "$type"
      ],
      type: "object",
      properties: {
        $type: {
          type": "string"
      },
      discriminator: {
        propertyName: "$type",
        mapping: {
          Rectangle: "#/components/schemas/Rectangle",
          Circle: "#/components/schemas/Circle"
        }
      }
    },
    Rectangle: {
      type: "object",
      allOf: [
        {
          "$ref": "#/components/schemas/Shape"
        }
      ],
      ...
    },
    Circle: {
      type: "object",
      allOf: [
        {
          "$ref": "#/components/schemas/Shape"
        }
      ],
      ...
    }
  }
}
```

And I have a union type of the subtypes like this:
```
type ShapeInput = Rectangle | Circle;
```
It would be nice if the subtypes included a field like these:
```
interface Rectangle {
    type: 'Rectangle';
   ....
}

interface Circle {
    type: 'Circle';
    ....
}
```

Is it possible to achieve this currently?

### PR DESCRIPTION
**Pull request by BaDo2001**
## Status

**READY**

## Description

Closes #423. 

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

### CODE REVIEW

**Comment by BaDo2001** [comment]
@anymaniax Could you please assign someone to review this? Thanks in advance.

**Comment by anymaniax** [comment]
I will take a look probably tomorrow or this Saturday

**Comment by anymaniax** [comment]
Hello @BaDo2001, from what I tested seems good thanks. Can you add an example with a discriminator and a test config with that generated? 

Also, it's a good first version but it's not handling discriminator in response and also multi-files refs

**Comment by BaDo2001** [comment]
@anymaniax I am quite new to swagger so could you please elaborate on that?

What does it mean that it's not handling discriminator in response?
Also is it possible to have multiple input files? I didn't know that.

I will try to improve this solution, thanks for the review.

**Comment by anymaniax** [comment]
You can keep it like that for now its a good first version. We will improve later on if needed. Just add some docs and tests if you can

**Comment by BaDo2001** [comment]
@anymaniax Where do you think the docs should go? I can't seem to find a good place for it.

**Comment by anymaniax** [comment]
@BaDo2001 no need to add something in the doc for that just add an example in the `samples` folder and a test in the `tests` folder

**Comment by BaDo2001** [comment]
@anymaniax Sorry it took so long, I had a lot on my plate recently. I added a basic example.

**Comment by anymaniax** [comment]
@BaDo2001 feel you. Will take a look this week

**Review by anymaniax — APPROVED** [review]
Thanks!

**Pull request merged**
