### PR TITLE
[REFACTOR] Use nullish coleasing

### PR DESCRIPTION
**Pull request by yekver**
Use modern nullish coleasing syntax `??` instead of `||` where this is possible

### CODE REVIEW

**Review by melloware — DISMISSED** [review]

**Review by CPatchane — DISMISSED** [review]
Great!

**Comment by anymaniax** [comment]
can you fix the merge conflict?

**Comment by yekver** [comment]
> can you fix the merge conflict?

fixed

**Review by anymaniax — APPROVED** [review]

**Comment by anymaniax** [comment]
Thanks 🎉

**Pull request merged**
