### PR TITLE
fix(core): capitalize http verb patch

### PR DESCRIPTION
**Pull request by hkfi**
## Status

READY

## Description

Changed the HTTP verb 'patch' to 'PATCH'. 
PATCH is the only HTTP method that is case sensitive. It needs to be capitalized to work.

## Related PRs

List related PRs against other branches:

None

## Todos

- [x] Tests
- [x] Documentation
- [x] Changelog Entry (unreleased)

### CODE REVIEW

**Comment by anymaniax** [comment]
I never had that issue. In which case do have that? An what http client do you use and if it’s a dependency which version?

**Comment by hkfi** [comment]
When using JavaScript's fetch.

Another person described here in the issues as well:
https://github.com/anymaniax/orval/issues/888

**Comment by anymaniax** [comment]
@hkfi the problem it's that currently done like that It would be a breaking change and you can uppercase all method in your custom instance. Would be better to create a fetch client no?

**Comment by anymaniax** [comment]
Then would be better to pass everything to uppercase no?

**Comment by Jacob-Roberts** [comment]
The only verb where uppercase is required is PATCH, so it doesn't need to be every verb updated as part of this PR, but yes it could be every verb

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
It should be every verb. They all should be uppercase

**Comment by melloware** [comment]
Looks like this is failing the ZOD compilation because `PathItemObject` from openapi-ts

https://github.com/drwpow/openapi-typescript/blob/43b1b69bc26ee333d0fed1f4aa702496c485dc01/packages/openapi-typescript/src/types.ts#L166-L187

**Pull request closed without merging**
