### PR TITLE
feat: Model filename casing

### PR DESCRIPTION
**Pull request by taisei-13046**
## Status

**READY**

## Description

This PR fixes https://github.com/anymaniax/orval/issues/1499

- generate schema file name with PascalCase.

## Related PRs

List related PRs against other branches:

| branch              | PR       |
| ------------------- | -------- |
| other_pr_production | [link]() |
| other_pr_master     | [link]() |

## Todos

- [x] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.

```bash
> git pull --prune
> git checkout <branch>
> grunt jasmine
```

1.

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@anymaniax @soartec-lab any reason not to think this is correct?  Looking at the ticket the file name definitely does not seem right?

**Comment by soartec-lab** [comment]
@melloware 
In my opinion, I thought that this was due to the file naming convention and that there was no problem with the current situation. 
After making this change, someone else may want to change the naming convention again. And I don't want to change the naming convention because it would be repetitive.

**Comment by taisei-13046** [comment]
@melloware @soartec-lab 
Thank you for commenting on this PR. When I first saw this issue https://github.com/anymaniax/orval/issues/1499, I felt the same way and decided to submit a PR. The reason is that I wanted the model file names to be generated in PascalCase.

However, as @soartec-lab mentioned, this depends on the naming conventions, so if it is not necessary, feel free to close this PR.

I really like this library, so I'd love to contribute again if I get the chance.

**Comment by soartec-lab** [comment]
@taisei-13046 
thank you. We always look forward to your contribution 🙌 

@melloware 
I think this should be closed, what do you think?

**Comment by melloware** [comment]
Closed

**Pull request closed without merging**
