### PR TITLE
fix: adjust SecondParameter utility type

### PR DESCRIPTION
**Pull request by victorboucher**
## Status

**READY**

## Description

Fixes the poorly typed SecondParameter utility type.

### CODE REVIEW

**Comment by melloware** [comment]
Can you please open an Issue ticket explaining what is poorly typed and show us how this ticket makes it better?

**Comment by melloware** [comment]
@soartec-lab since this affects SWR can you review this change?

**Review by melloware — APPROVED** [review]

**Comment by soartec-lab** [comment]
@melloware 

Of cource 👍 I'll review this, so could you assign me reviewer for this PR ?

**Review by soartec-lab — COMMENTED** [review]
@victorboucher @melloware 

This change will affect the case where `global mutator` is used, and I don't think it will affect the generated `swr` custom hook alone.
At the same time, we thought it would have the following advantages:

- Can be expressed in a simpler and more understandable form
- Being able to remove eslint disable

However, this change forces a fixed order of arguments in the `global mutator` function definition. This will result in unintentionally breaking changes for existing users, so it may be wise to avoid making this change unless it is a more important change.

**Review by soartec-lab — COMMENTED** [review]
I removed the approve because I was concerned about the content being different from what I was getting the mention for. Let me confirm about `global mutator`.
this change forces a fixed order of arguments in the `global mutator` function definition.
This would result in an unintentionally breaking change for existing users, so it might be wise not to make this change unless it's a more significant change. What do you think?

**Comment by melloware** [comment]
No problem just let me know what your final decision is.

**Comment by soartec-lab** [comment]
@melloware 
Previously, `never` was returned if the second argument did not exist, but we investigated the impact of changing it to `undefined`.

In the first place, there will be no mismatch due to the case where the second argument does not exist, and even if it were to happen, there would be no problem because the type was specified as `never | undefined` in the function used. so, i agree with merging PR.

**Pull request merged**
