### PR TITLE
feat(objectParams): use single object params option

### PR DESCRIPTION
**Pull request by pivaszbs**
## Status

Ready

## Description

A few sentences describing the overall goals of the pull request's commits.

## Related PRs

List related PRs against other branches:

| branch              | PR       |
| ------------------- | -------- |
| other_pr_production | [link]() |
| other_pr_master     | [link]() |

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.

```bash
> git pull --prune
> git checkout <branch>
> grunt jasmine
```

1.

### CODE REVIEW

**Comment by yekver** [comment]
Seems like this PR is linked to #281

**Comment by anymaniax** [comment]
Hello @pivaszbs, thanks for the pull request. Wanted to do it for a while will need to take a bit of time to review this. Probably next week.

**Comment by anymaniax** [comment]
can be introduced with v7 #434 and with your own template or I would prefer an option in the config to add this to all the current template

**Comment by jrozbicki** [comment]
@anymaniax option in config similar to [openapi-typescript-codegen --useOptions](https://github.com/ferdikoomen/openapi-typescript-codegen/blob/master/docs/arguments-vs-object-style.md) would be awesome! By the looks of it, this seems to be last missing piece blocking us from moving to orval

**Comment by Marcel-G** [comment]
`useNamedParameters` option has been added: https://github.com/anymaniax/orval/pull/914

**Pull request closed without merging**
