### PR TITLE
[PROPOSAL] version compatibility

### PR DESCRIPTION
**Pull request by anymaniax**
## Status

**READY**

## Description
Orval can now automatically check the package.json and the version of the client. With that, it's able to generate a different version of the code by version

### CODE REVIEW

**Comment by anymaniax** [comment]
What do you think of this @CPatchane @yekver @melloware?

**Comment by melloware** [comment]
This is super slick. I assume you tested it and it works?

**Comment by anymaniax** [comment]
Sure it works 😀

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Awesome work.  You rock. Orval is letting me impress my client with how fast I can turn around API changes 👍🏻

**Comment by CPatchane** [comment]
Seems great for better maintenance also 👍

**Pull request closed without merging**
