### PR TITLE
feat(core): option to disable creating index files

### PR DESCRIPTION
**Pull request by codebutler**
## Status

**READY**

## Description

Adds an option to disable creating `index.ts` files. 

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce

Set option:

```ts
{
    output: {
        indexFiles: false
    }
}
```

### CODE REVIEW

**Comment by codebutler** [comment]
My motivation for this change: When using vite there's no tree-shaking during development, so having an index barrel file causes every model to be fetched before the app can load. In a big app this is thousands of requests.

**Comment by anymaniax** [comment]
@codebutler seems really great I am just not sure about the name of the options do you have other idea then “index”? Personally nothing come to my mind

**Comment by codebutler** [comment]
> @codebutler seems really great I am just not sure about the name of the options do you have other idea then “index”? Personally nothing come to my mind

It's also known as a [barrel file](https://basarat.gitbook.io/typescript/main-1/barrel).  Something like `createIndex`, `createIndexFile`, or `createBarrelFile`?

**Review by anymaniax — APPROVED** [review]
Thanks @codebutler !

**Pull request merged**
