### PR TITLE
fix(generator): apply nullish? operator in schema.ts

### PR DESCRIPTION
**Pull request by Talor-A**
## Status

**READY**

## Description
fixes https://github.com/anymaniax/orval/issues/259 . I don't know if this is a "proper" fix but it solves the example reproduction case in the issue body. 

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce
see issue for details. the files specified will fail yo

### CODE REVIEW

**Comment by Talor-A** [comment]
actually, this fixes the example case but in my spec (it's proprietary) I get only interfaces generated, and no hooks/methods/mocks even though the generation succeeds.

**Comment by Talor-A** [comment]
converting to draft, need a better solution.

**Comment by Talor-A** [comment]
reopening as I experienced 2 related bugs, this fixes the first.

**Comment by anymaniax** [comment]
Hey @Talor-A, mmh weird this case shouldn't happen I need to investigate that more. Will have time this weekend normally

**Comment by Talor-A** [comment]
ok no problem. I've pulled this commit into my fork as it fixes it for my situation, but I don't doubt there's a better solution. thanks for the response!

**Comment by anymaniax** [comment]
thanks fixed with an other pull request

**Pull request closed without merging**
