### PR TITLE
fix(deps): updated dependencies

### PR DESCRIPTION
**Pull request by melloware**
## Status
**READY**

## Description
Just updating dependencies to newer versions.

### CODE REVIEW

**Comment by melloware** [comment]
Updating ESLint now is catching this issue: https://github.com/anymaniax/orval/issues/177

**Comment by anymaniax** [comment]
@melloware the failing test is because of me. I added a new one that catch that problem indeed

**Comment by anymaniax** [comment]
Should be fixed right now

**Comment by melloware** [comment]
Thanks I rebased my branch and tests are passing now.

**Pull request merged**
