### PR TITLE
fix: add support for delete body

### PR DESCRIPTION
**Pull request by RichardLindhout**
Fixes https://github.com/anymaniax/orval/issues/254

### CODE REVIEW

**Comment by anymaniax** [comment]
Thanks for the merge request but it will cause a problem with the Axios generation that don't accept a body for a delete method

**Comment by anymaniax** [comment]
Will also need to update the client generators to handle that case and pass it in the axios config with the property data

**Comment by anymaniax** [comment]
I just did the implementation and it will be in the next release so I close this pull request. Thanks

**Comment by RichardLindhout** [comment]
Thank you!

**Pull request closed without merging**
