### PR TITLE
fix(form-data): handling array items

### PR DESCRIPTION
**Pull request by BijanRegmi**
## Status

**READY**

## Description

Fixes: #845 

Formdata only supports either string or blob types. So items of an array should be converted to string before adding them to the form.

## Todos

- [x] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Review by hariacharya80 — APPROVED** [review]
Nice catch!

**Comment by melloware** [comment]
Looks like a formatting issue. Can you run `npm run format` please?

**Comment by BijanRegmi** [comment]
> I see that the approved changes sets the data as a JSON string when `itemSchema.type === 'object'`, This gets rid of the error, but doesn't realy make it form-data. Shouldn't each of the properties of the object also be iterated? And also add an array suffix to the key?
> 
> So that the end result looks something like this for the form data key: `<arrayFieldName>[<arrayIndex>].<objectPropertyName>`

I think it's a personal opinion kind of thing. Surely `<key1>.<key2>` makes more sense for formdata but in most of the cases when transferring json data in formdata most tend to `JSON.stringify` the data and set `content-type` of the data to `application/json`

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@Ultre00 do you want to review the latest changes?

**Comment by Ultre00** [comment]
Isn't this change only related to formdata anyway? I don't see how setting `content-type` to `application/json` solves that issue as there was never a problem with that `content-type`. In my case, I couldn't use `application/json` as I want to send some files in the same request, so I am using `multipart/form-data`.  I know there isn't really a standard defined on how to handle nested objects/arrays. What I suggested is just what .NET expects, I guess.

I don't think there is anything else to review. Only Main is merged into this branch.

**Comment by melloware** [comment]
@Ultre00 @BijanRegmi where are we with this PR?  Is there more work to be done?

**Comment by BijanRegmi** [comment]
It's ready to be merged

**Pull request merged**
