### PR TITLE
Fix TVariables

### PR DESCRIPTION
**Pull request by Maxim-Mazurok**
## Status

**READY/WIP**

## Description

Based on https://github.com/anymaniax/orval/pull/931, addresses https://github.com/anymaniax/orval/issues/857, most likely in a wrong way but it works for me, so just documenting it here for the future

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce

Not sure how to reproduce, but the generated code is mentioned in https://github.com/anymaniax/orval/issues/857

### CODE REVIEW

**Comment by anymaniax** [comment]
Hello @Maxim-Mazurok, why removing TVariables? Did you test with the other framework if still work well? And #931 is not useful anymore?

**Comment by Maxim-Mazurok** [comment]
I think that #931 is more useful than this, I just had to do these fixes so we can apply patches and move forward, didn't have time to do PRs properly, sorry about that. I think only this commit from this PR is relevant to the issue: [`8390c74` (#932)](https://github.com/anymaniax/orval/pull/932/commits/8390c74aa54caa741b76edc8cf0d9fa6728ab206)

I don't know why `TVariables` exists in the first place, what's the use-case there, we've been using this patch to address #857 for a while and haven't run into issues. I haven't tried with other frameworks.

**Comment by melloware** [comment]
@Maxim-Mazurok should this be closed in favor of your new PR: https://github.com/anymaniax/orval/pull/1085

**Comment by Maxim-Mazurok** [comment]
> @Maxim-Mazurok should this be closed in favor of your new PR: #1085

Ah, yes, I forgot that this PR exists :)

**Pull request closed without merging**
