### PR TITLE
improve url validation

### PR DESCRIPTION
**Pull request by davidsonsns**
following the tip below to validate `localhost` URLs properly

https://github.com/validatorjs/validator.js/issues/1609#issuecomment-780685689

## Status

**READY**

## Description
improve URL validation

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
https://github.com/davidsonsns/orval/tree/url-validation-improvement | #219 

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

### CODE REVIEW

**Comment by anymaniax** [comment]
can you add that everywhere isUrl is used, please?

**Comment by davidsonsns** [comment]
> can you add that everywhere isUrl is used, please?

ohh for sure! let me check it out!

**Comment by davidsonsns** [comment]
@anymaniax ready again 🙌🏻

**Review by anymaniax — APPROVED** [review]
Thanks 🎉

**Pull request merged**
