### PR TITLE
feat: zod generator

### PR DESCRIPTION
**Pull request by stijnvanhulle**
## Status

WIP

## Description

A new generator that will convert the schema to a Zod object. 
This is more of a tryout to see if it's possible to convert to Zod, at this moment it only contains the types needed for doing API calls and not the ones that are generated for Typescript. 

In the future, it would be nice to generate the models for Typescript and for Zod.

## Related PRs

Based on https://github.com/anymaniax/orval/pull/415

## Todos

- [ ] Tests
- [ ] Test on a bigger schema 
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Examples

```javascript
import * as zod from 'zod';

/**
 * @summary List all pets
 */
export const listPetsParams = zod.object({
  limit: zod.string().optional(),
  sort: zod.enum(['name', '-name', 'email', '-email']),
  version: zod.number().optional(),
});

export const listPetsHeader = zod.object({
  'X-EXAMPLE': zod.enum(['ONE', 'TWO', 'THREE']),
});

/**
 * @summary Create a pet
 */
export const createPetsParams = zod.object({
  limit: zod.string().optional(),
  sort: zod.enum(['name', '-name', 'email', '-email']),
  version: zod.number().optional(),
});

export const createPetsBody = zod.object({
  name: zod.string(),
  tag: zod.string(),
});

export const createPetsHeader = zod.object({
  'X-EXAMPLE': zod.enum(['ONE', 'TWO', 'THREE']),
});

/**
 * @summary Info for a specific pet
 */
export const showPetByIdParams = zod.object({
  petId: zod.string(),
  testId: zod.string(),
  version: zod.number().optional(),
});
```

### CODE REVIEW

**Comment by melloware** [comment]
You should open a matching issue ticket so it can link this PR in the future and for release notes.

**Comment by atreya2011** [comment]
@stijnvanhulle Nice!

@anymaniax Is it possible to generate both `react-query` and `zod` related code using the current config? (provided this PR is ready and merged 🙂 )

**Comment by gunnartorfis** [comment]
Is there anything we can do to help this get merged? 😇

**Comment by anymaniax** [comment]
I am currently extracting the orval core to be able to write any kind of generator like this one easily and even be able to create your own package directly with it.

**Comment by anymaniax** [comment]
Hello @gunnartorfis @stijnvanhulle, you can now check the new architecture and create your own client with the extracted core. The current version is `@orval/core@6.11.0-alpha.1`.

**Pull request closed without merging**
