### PR TITLE
update to yarn 4.2.2

### PR DESCRIPTION
**Pull request by karlismelderis-mckinsey**
## Status

**READY**

## Description

Update project to yarn v4

Yarn versions are controlled by corepack now
https://yarnpkg.com/getting-started/install

There are a plenty [breaking changes](https://yarnpkg.com/migration/guide) but quick scan through code didn't raised any red flags hence only lock fine has changed

### CODE REVIEW

**Comment by melloware** [comment]
Looks like tests are failing?

**Comment by anymaniax** [comment]
I would prefer migrating to bun at this point

**Comment by karlismelderis-mckinsey** [comment]
> I would prefer migrate to bun at this point

I'll leave it up to you but do keep in mind that Installing another tool and learning how tests and package management work in Bun will discourage people (at least me) for contributing

I've already invested enough time to re-learh yarn after using pnpm for a while and I don't want to go through it one more time

if Bun survives Youtube/Blog/Facebook hype and is still around after couple more years 
if Bun roadmap and release cycle becomes more stable and looks like NodeJS (read more corporate friendly)

P.S. I was surprised to find that Orval has multiple layers of yarn workspaces
Should be possible to specify them all in root but I'll leave it for another PR

**Comment by karlismelderis-mckinsey** [comment]
I have another side question
any reason to introduce `NX` -> `nx-fastify-react`
it does pull in quite a bit of dependencies and requires attention to follow NX changes and run migrations

NX is a great tool but not sure you really need it for one single sample code

**Comment by melloware** [comment]
@soartec-lab did you bring in fastify?  Or was it always there?

**Comment by soartec-lab** [comment]
@melloware 

No, I haven't added it.
Actually, when I re-run `orval` in `nx-fastify-react`, it doesn't work, so I exclude it in `turborepo`.

https://github.com/anymaniax/orval/blob/master/samples/package.json#L13

The `nx-fastify-react` is not maintained and is broken, so i agree to delete it.

**Comment by soartec-lab** [comment]
Also, I agree with using `bun`. I've used it in other projects and it's great. This is because it can be used while maintaining compatibility and provides a better development experience.

However, since cooperation with `dependabot` is not yet supported, it is necessary to support that as well, so it is better to use `yarn v4` first, and then take the time to replace it with `bun`.

**Comment by soartec-lab** [comment]
@karlismelderis-mckinsey @melloware 

I'll make PR for `nx-fastify-react` delete.

**Comment by soartec-lab** [comment]
I''m working on it here, but it's still a work in progress. I will open it when completed

https://github.com/anymaniax/orval/pull/1408

**Comment by karlismelderis-mckinsey** [comment]
Have you considering to replace `dependabot` with [renovate](https://docs.renovatebot.com/)?

I find it's configuration more flexible and it discovers all package.json files in the repo without any extra configuration
also least last time I tried `dependabot` wasn't able to keep pnpm lock files up to date and extra scripting was required

**Comment by melloware** [comment]
Looks like merge conflict?

**Comment by karlismelderis-mckinsey** [comment]
can we collect approvals and I'll rebase one more time
due to amount of changes merged it will be tough race to keep this PR without conflicts 😉

**Comment by melloware** [comment]
@karlismelderis-mckinsey if you update i will merge this PR once its ready to go.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
I have tried everything `corepack enable` etc all the YARN instructions yet i still get this on `yarn dev`

```
@orval/core:dev: DTS Build start
orval:dev: C:\dev\melloware\orval\packages\core\node_modules\chalk\source\index.js:2
orval:dev: const ansiStyles = require('ansi-styles');
orval:dev:                    ^
orval:dev:
orval:dev: Error [ERR_REQUIRE_ESM]: require() of ES Module C:\dev\melloware\orval\node_modules\ansi-styles\index.js from C:\dev\melloware\orval\packages\core\node_modules\chalk\source\index.js not supported.
orval:dev: Instead change the require of C:\dev\melloware\orval\node_modules\ansi-styles\index.js in C:\dev\melloware\orval\packages\core\node_modules\chalk\source\index.js to a dynamic import() which is available in all CommonJS modules.
orval:dev:     at Object.<anonymous> (C:\dev\melloware\orval\packages\core\node_modules\chalk\source\index.js:2:20) {
orval:dev:   code: 'ERR_REQUIRE_ESM'
orval:dev: }
orval:dev:
orval:dev: Node.js v20.14.0
@orval/core:dev: DTS ⚡️ Build success in 1773ms
```

Any thoughts?

**Pull request merged**
