### PR TITLE
fix(useNamedParameters): use operationName instead of operationId

### PR DESCRIPTION
**Pull request by Marcel-G**
## Status

**READY**

## Description

This feature was using `operationId` to construct the `PathParameters` name. For consistency, it would be better to use `operationName` as it can be mapped to something by users.

## Related PRs

List related PRs against other branches:

| branch              | PR       |
| ------------------- | -------- |
| other_pr_production | [link]() |
| other_pr_master     | [link]() |

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce

Outline the steps to test or reproduce the PR here.

```bash
> git pull --prune
> git checkout <branch>
> grunt jasmine
```

1.

### CODE REVIEW

**Comment by anymaniax** [comment]
Hello @Marcel-G seems good but could be a breaking change in some cases no?

**Comment by Marcel-G** [comment]
> Hello @Marcel-G seems good but could be a breaking change in some cases no?

Technically yes, since the path parameter types are public and would effect consumers who:
- Are already using `useNamedParameters` and
- Have operations named with `operationId` or custom naming mutator and
- Are directly importing the Path parameters model type in their projects

**Comment by anymaniax** [comment]
@Marcel-G should be a really little number of ppl tho no?

**Comment by Marcel-G** [comment]
> @Marcel-G should be a really little number of ppl tho no?

Yes very few I imagine

**Review by anymaniax — APPROVED** [review]

**Comment by anymaniax** [comment]
@Marcel-G I don't know if you are often on discord but if you could be discuss there with the other maintainers would be great

**Pull request merged**
