### PR TITLE
fix(enum): add suffix AsOf when generating the enum

### PR DESCRIPTION
**Pull request by dennisroche**
## Status

**READY**

## Description
Fixes https://github.com/anymaniax/orval/issues/245

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

### CODE REVIEW

**Comment by anymaniax** [comment]
The way you did it will rename all enum. We just need to add the suffix allOf when it's in a allOf

**Comment by dennisroche** [comment]
ok, misunderstood the problem. how do you detect when it is a `allOf`?

**Comment by dennisroche** [comment]
Are you sure that this doesn't need to apply to all `enum`? 

A simple `enum` schema:

```
components:
  schemas:
    LogEventLevel:
      enum:
        - Verbose
        - Debug
        - Information
        - Warning
        - Error
        - Fatal
      type: string
```

will generate:

```
export type LogEventLevel = 'Verbose' | 'Debug' | 'Information' | 'Warning' | 'Error' | 'Fatal';

export const LogEventLevel = {
  Verbose: 'Verbose' as LogEventLevel,
  Debug: 'Debug' as LogEventLevel,
  Information: 'Information' as LogEventLevel,
  Warning: 'Warning' as LogEventLevel,
  Error: 'Error' as LogEventLevel,
  Fatal: 'Fatal' as LogEventLevel,
};
```

and that causes a `@typescript-eslint/no-redeclare` error when we build our app.

**Comment by anymaniax** [comment]
Yes it's mostly to compile simple JavaScript but could be interesting to add a rule to disable eslint for that one. Explanation [here](https://maxheiber.medium.com/alternatives-to-typescript-enums-50e4c16600b1)

**Comment by dennisroche** [comment]
> Yes it's mostly to compile simple JavaScript but could be interesting to add a rule to disable eslint for that one. Explanation [here](https://maxheiber.medium.com/alternatives-to-typescript-enums-50e4c16600b1)

Thanks for sharing that; agree it would be better to disable that `eslint` for the generated model.

**Pull request closed without merging**
