### PR TITLE
fix(core): inconsistent kebab casing comparison

### LINKED ISSUE #936: Incomplete HTTP calls file causing typescript warnings on files generated by orval
## What are the steps to reproduce this issue?

Use orval to generate a client with a custom mutator (https://orval.dev/guides/custom-client) and PascalCase tags inside the swagger.json.  For example a tag of "PetTag".  

I have laid out an example below (all files attached [Examples.zip](https://github.com/anymaniax/orval/files/12595741/Examples.zip)) to demonstrate the issue.

### Example orval.config.js.  References a custom mutator and a mode of tags-split.  
```javascript
 module.exports = {
   'petstore-file': {
     input: './swagger.json',
     output: {
		 target: "./petstore.ts",
		 mode: "tags-split",
		override: {
         mutator: {
           path: './customInstance.ts',
           name: 'customInstance',
         },
       },
	 }
   },
 };
```

### This swagger.json causes problems.
Swagger.json is simply (https://petstore3.swagger.io/api/v3/openapi.json), but with the "pet" tag renamed to "PetTag".
```json
"tags": [
    {
      "name": "PetTag",
      "description": "Everything about your Pets",
      "externalDocs": {
        "description": "Find out more",
        "url": "http://swagger.io"
      }
    }
    ...
    ..
  ],
   ....
  "paths": {
    "/pet": {
      "put": {
        "tags": ["PetTag"],
        ....
      }
      ....
    }
    ....
  }
```

### This original swagger.json works fine with problems.
```json
"tags": [
    {
      "name": "pet",
      "description": "Everything about your Pets",
      "externalDocs": {
        "description": "Find out more",
        "url": "http://swagger.io"
      }
    }
    ...
    ..
  ],
   ....
  "paths": {
    "/pet": {
      "put": {
        "tags": ["pet"],
        ....
      }
      ....
    }
    ....
  }
```

## What happens?

The file containing the HTTP calls is incomplete, resulting in typescript warnings (which in my case ultimately cause my project build to fail): 

'Awaited' is declared but never used.

It appears that the section below the non-exported Awaited type is not written out.

### Actual output in pet-tag.ts
```typescript
type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

//There's nothing here...
```

### Output I expect in pet-tag.ts
```typescript
type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UpdatePetResult = NonNullable<Awaited<ReturnType<typeof updatePet>>>
export type AddPetResult = NonNullable<Awaited<ReturnType<typeof addPet>>>
export type FindPetsByStatusResult = NonNullable<Awaited<ReturnType<typeof findPetsByStatus>>>
export type FindPetsByTagsResult = NonNullable<Awaited<ReturnType<typeof findPetsByTags>>>
export type GetPetByIdResult = NonNullable<Awaited<ReturnType<typeof getPetById>>>
export type UpdatePetWithFormResult = NonNullable<Awaited<ReturnType<typeof updatePetWithForm>>>
export type DeletePetResult = NonNullable<Awaited<ReturnType<typeof deletePet>>>
export type UploadFileResult = NonNullable<Awaited<ReturnType<typeof uploadFile>>>

```

## Any logs, error output, etc?

No errors displayed.

## Any other comments?

I think this is a bug relating to the kebab casing that is done to the tags for tag splitting the files.  In the screenshot below, you can see that the operation names get filtered by tags, where that tags array "includes" a tag.

image

The tags array in builder.operations contains the unmodified tags straight from the openapi json (i.e "PetTag") and the tag we are comparing it to is kebab-cased, because that's what happens in generateTargetTags():
 tags.includes(tag))
 
As:
tags = ["PetTag"]
tag = "pet-tag"

we can see that the operations are going to be filtered out.

I can probably fix this myself and submit a PR, but would welcome any thoughts from those with a better understanding of the codebase first.
My fix would probably be simply to map the tags array into kebab case in the before doing this comparison, but I don't really know what, if any, unintended side effects that might cause.

## What versions are you using?

**Operating System:** Windows 10
**Package Version:** 6.17.0
**Browser Version:** N/A

[Examples.zip](https://github.com/anymaniax/orval/files/12595741/Examples.zip)

### PR DESCRIPTION
**Pull request by fergiektid**
## Status
READY

Fix #936 

## Description

This PR aims to resolve issue #936.  Which causes potentially invalid typescript to be generated by Orval.  Need to ensure that we are comparing like for like when searching the array of tags for a specific tag.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce
https://github.com/anymaniax/orval/issues/936#issue-1894114763

### CODE REVIEW

**Comment by anymaniax** [comment]
Hello @fergiektid, thanks for the pr. We should kebab both side to be sure no?

**Comment by fergiektid** [comment]
> Hello @fergiektid, thanks for the pr. We should kebab both side to be sure no?

Yes, In this specific instance, I don't think we need to because it's already been called for the right hand side.  But I don't see any harm in doing it again as a safety net against future refactoring.  

I've added a test for the kebab case routine to ensure that the kebab routine remains Idempotent, since we are potentially calling it multiple again with input which has already been through the routine.

I have updated the PR.

**Review by anymaniax — APPROVED** [review]
Thanks!

**Comment by anymaniax** [comment]
Can you resolve the conflict pls?

**Review by melloware — APPROVED** [review]

**Review by melloware — APPROVED** [review]

**Pull request merged**
